name: Deploy Lambda Functions

on:
  push:
    branches:
      - main

env:
  AWS_REGION: ap-southeast-2
  AWS_ROLE_TO_ASSUME: arn:aws:iam::941377134816:role/gitactions-lambda-role

permissions:
  id-token: write
  contents: read
  
jobs:
  deploy:
    name: Deploy Lambda Functions
    runs-on: ubuntu-latest
    environment: production
    strategy:
      matrix:
        function_name: [SuncreamReminder, UVRequest-V1] # Add more functions as needed

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'

    - name: Install dependencies
      run: |
        pip install awscli pytest

    - name: Run unit tests
      run: |
        cd backend/${{ matrix.function_name }}
        if ls test_*.py 1> /dev/null 2>&1; then
          echo "Found test files, running tests..."
          python -m pytest test_*.py -v
        else
          echo "No test files found for ${{ matrix.function_name }}, skipping tests."
        fi

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-region: ${{ env.AWS_REGION }}
        role-to-assume: ${{ env.AWS_ROLE_TO_ASSUME }}
        role-session-name: GitHubActionsLambdaDeployment

    - name: Zip the Lambda function
      run: |
        cd backend/${{ matrix.function_name }}
        zip -r ../../${{ matrix.function_name }}.zip lambda_function.py

    - name: Check if Lambda function exists
      id: check_lambda
      run: |
        if aws lambda get-function --function-name ${{ matrix.function_name }}; then
          echo "lambda_exists=true" >> $GITHUB_OUTPUT
        else
          echo "lambda_exists=false" >> $GITHUB_OUTPUT
        fi

    - name: Create or Update Lambda function
      run: |
        if [ "${{ steps.check_lambda.outputs.lambda_exists }}" == "false" ]; then
          echo "Creating Lambda function..."
          aws lambda create-function --function-name ${{ matrix.function_name }} \
            --runtime python3.13 \
            --role ${{ env.AWS_ROLE_TO_ASSUME }} \
            --handler lambda_function.lambda_handler \
            --zip-file fileb://${{ matrix.function_name }}.zip
        else
          echo "Updating Lambda function..."
          aws lambda update-function-code \
            --function-name ${{ matrix.function_name }} \
            --zip-file fileb://${{ matrix.function_name }}.zip --publish
        fi

    - name: Clean up
      run: rm ${{ matrix.function_name }}.zip